name: CI GdUnit3 on Godot Mono 3.3.x

on:
  push:
    paths-ignore:
      - '**.yml'
      - '**.jpg'
      - '**.png'
      - '**.md'
  workflow_dispatch:

jobs:
  testing:
    strategy:
      matrix:
        godot: [mono-3.4.4]

    name: GdUnit3 Selftest on Godot ${{ matrix.godot }}
    runs-on: ubuntu-latest
    continue-on-error: true
    container:
      image: barichello/godot-ci:${{ matrix.godot }}

    steps:
      - name: Checkout GdUnit3 Plugin
        if: ${{ !cancelled() }}
        uses: actions/checkout@v3
        with:
          repository: MikeSchulze/gdUnit3

      - name: Checkout GdUnit3Mono
        if: ${{ !cancelled() }}
        uses: actions/checkout@v3
        with:
          lfs: true
          path: mono

      - name: Patch Project files
        if: ${{ !cancelled() }}
        run: |
          rm -rf gdUnit3.cs*
          cp ./mono/gdUnit3Mono.csproj gdUnit3.csproj
          mv ./mono/TestRunner.* .
          chmod 777 ./mono/runtests.sh

      - name: Setup .NET
        if: ${{ !cancelled() }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Compile
        run: |
          dotnet restore gdUnit3.csproj
          mkdir -p .mono/assemblies/Debug
          cp /usr/local/bin/GodotSharp/Api/Release/* .mono/assemblies/Debug
          dotnet build -verbosity:m

      - name: Run Selftest
        if: ${{ !cancelled() }}
        timeout-minutes: 10
        env:
          GODOT_BIN: "/usr/local/bin/godot"
        shell: bash
        run: ./mono/runtests.sh -a res://mono/test

      - name: Publish Test Reports
        if: ${{ !cancelled() }}
        uses: ./.github/actions/publish-test-report
        with:
          report-name: Test Report (${{ matrix.godot }})

      - name: Collect Test Artifacts
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v2
        with:
          name: Report_${{ matrix.godot }}
          path: reports/**