name: CI GdUnit3 on Godot Mono 3.3.x

on:
  pull_request:
    paths-ignore:
      - '**.yml'
      - '**.jpg'
      - '**.png'
      - '**.md'
  workflow_dispatch:

env:
  GODOT_BIN: "/usr/local/bin/godot"

concurrency:
  group: ci-pr-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  unit-test:
    strategy:
      fail-fast: false
      matrix:
        godot-build: ['mono-']
        godot-version: [ 3.4.4] # 3.4.3 is missing on barichello/godot-ci

    name: "CI on Godot ${{ matrix.godot-build }}v${{ matrix.godot-version }}"
    runs-on: ubuntu-latest
    timeout-minutes: 6
    continue-on-error: false
    container:
      image: barichello/godot-ci:${{ matrix.godot-build }}${{ matrix.godot-version }}

    steps:
      - name: "Checkout GdUnit3 Plugin"
        if: ${{ !cancelled() }}
        uses: actions/checkout@v3
        with:
          repository: MikeSchulze/gdUnit3

      - name: "Checkout GdUnit3Mono"
        if: ${{ !cancelled() }}
        uses: actions/checkout@v3
        with:
          lfs: true
          path: mono

      - name: "Patch Project"
        if: ${{ !cancelled() }}
        run: |
          rm -rf gdUnit3.csproj
          rm -rf gdUnit3.sln
          cp ./mono/gdUnit3Mono.csproj gdUnit3.csproj
          rm -rf addons/gdUnit3/test/
          mv mono/test ./test
          
        # sed -i 's+config/name="gdUnit3"+config/name="gdUnit3Mono"+g' project.godot

      - name: "Update Project"
        if: ${{ !cancelled() }}
        timeout-minutes: 1
        continue-on-error: true # we still ignore the timeout, the script is not quit and we run into a timeout
        run: |
          ${{ env.GODOT_BIN }} -e --path . -s res://addons/gdUnit3/src/core/scan_project.gd --no-window

      - name: "Setup .NET"
        if: ${{ !cancelled() }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: "Compile C#"
        timeout-minutes: 1
        run: |
          dotnet restore gdUnit3.csproj
          mkdir -p .mono/assemblies/Debug
          cp /usr/local/bin/GodotSharp/Api/Release/* .mono/assemblies/Debug
          dotnet build -verbosity:m

      - name: "Run Unit Test"
        if: ${{ !cancelled() }}
        timeout-minutes: 10
        uses: ./.github/actions/unit-test
        with:
          godot-bin: ${{ env.GODOT_BIN }}
          test-includes: "res://test"

      - name: "Publish Unit Test Reports"
        if: ${{ !cancelled() }}
        uses: ./.github/actions/publish-test-report
        with:
          report-name: ${{ matrix.godot-build }}${{ matrix.godot-version }}

      - name: "Upload Unit Test Reports"
        if: ${{ !cancelled() }}
        uses: ./.github/actions/upload-test-report
        with:
          report-name: ${{ matrix.godot-build }}${{ matrix.godot-version }}
